### ISSUE TITLE
页面语言, 显示

### ISSUE THREAD

**Issue by SlimeNull** [whitebearcode/typecho-bearsimple#1]
1. 页面语言选择按钮的位置不雅, 在 PC 端, 它应该处于页面头部最右侧, 而不是标题下方. 如果处于标题下方, 那么我建议将它的高度调低一些. 最好的处理方式是提供一个配置项, 让用户选择它的位置.
2. 手机端中, 导航目录应该默认关闭才对.

**Comment by whitebearcode** [comment]
好的，已记录，将在后续跟进。
