### ISSUE TITLE
主题启用失败

### ISSUE THREAD

**Issue by Dagwbl** [whitebearcode/typecho-bearsimple#14]
目前版本是1.2rc，启用主题后，刷新了一下，就直接报错了。
主题采用的master2分支的版本。
![image](https://user-images.githubusercontent.com/39078825/153466202-6f784277-885b-4545-9a55-809198d9983d.png)
刷新了一下，准备进前台安装核心，主题设置界面就报错了，求老哥帮帮忙。

**Comment by whitebearcode** [comment]
可在https://download.bearlab.eu/Typecho/Templates/Bearsimple/中下载Bearsimple_v1.9.6_compatible.zip
并在/themes/目录解压
出现这个的原因大多是程序版本不兼容所致

**Comment by Dagwbl** [comment]
> 可在https://download.bearlab.eu/Typecho/Templates/Bearsimple/ 中下载Bearsimple_v1.9.6_compatible.zip 并在/themes/目录解压 出现这个的原因大多是程序版本不兼容所致

感谢，重新下载部署了一下，成功应用了
