### ISSUE TITLE
细节优化，友情链接页面

### ISSUE THREAD

**Issue by Sualiu** [whitebearcode/typecho-bearsimple#16]
友情链接页面显示的次序依次是：站点名称、站点介绍、站点图标和站点名称。
![IMG_20220415_071452](https://user-images.githubusercontent.com/42514208/163492177-c4fdca56-9fa8-4c2e-91f4-dcbeeb16aafb.jpg)

但是在实际的使用当中，多是添加个人博客类友链。

最后一栏  站点图标和站点名称  中的站点名称可否改为自定义名称，以便改为博客作者的名字。这样子可能会更加好看一些？

**Comment by whitebearcode** [comment]
你好，最后一栏站点名称你可自定义填写，不一定要站点名称的，只是文字表述为站点名称

**Comment by i-loli** [comment]
好的，谢谢。麻烦了……

**Comment by whitebearcode** [comment]
> > 在页面中添加友链时使用格式：
> 
> `<li>网站名称</li>` `<li>网站地址</li>` `<li>网站图标</li>` `<li>网站描述</li>`
> 
> 四个一体，多个友链只需按照格式添加即可。
> 
> 这是格式，如果我修改了 网站名称，那么显示出来的最后一栏会保持和 网站名称 同步。如何自定义？

第一行是第一行，最后一行是最后一行，你第一行网站名称设为ABC，最后一行网站描述设为CBA，两者不会互相干扰，逻辑上应该是这样的，如果你的不是，请继续回复，我这里有空看一下这个问题

**Comment by Sualiu** [comment]
是的，第一行的 网站名称 和最后一行的 网站描述 并不会互相干扰。
可是，我的问题并不是这两者的干扰问题。
![IMG_20220419_180602](https://user-images.githubusercontent.com/42514208/163980855-4e1993c6-6105-4e5a-9533-cc7d07e4e2e5.jpg)
如图，我用红色标注的内容。
每一个友链中的这两行内容总是一样的，最后一行总是 网站名称 。 
我的提议是 自定义每一个友链中最后一个标红框的内容。如图
![IMG_20220419_180947](https://user-images.githubusercontent.com/42514208/163981798-b7e901a5-e4b0-4138-97c8-ce098b52d15b.jpg)

**Comment by whitebearcode** [comment]
你可以不用网站名称，你写什么都可以的

**Comment by Sualiu** [comment]
好吧。谢谢！
