### ISSUE TITLE
界面优化, 功能建议

### ISSUE THREAD

**Issue by SlimeNull** [whitebearcode/typecho-bearsimple#2]
1. 主页导航目录的 "页面" 下拉菜单, 建议提供一个设置项, 是将其以下拉菜单的形式呈现, 或者直接作为导航的链接, 或者不显示. 并提供一些简单的自定义功能, 例如使用户能够设置显示的页面有哪些.
2. 建议网页滚动条颜色可更改为透明色 (虽然用户可以直接通过 css 实现, 但还是推荐直接提供配置项
3. 提供简单的管理功能, 例如在导航页面提供link直接跳转到后台管理, 提供链接直接指向"写文章".

**Comment by whitebearcode** [comment]
1、这个在顶部设置中已有选项
2、后续版本加入
3、后续版本加入，目前在登陆状态下文章内页会有编撰文章按钮
