### ISSUE TITLE
Class 'Utils\Helper' not found

### ISSUE THREAD

**Issue by Xuminhua** [whitebearcode/typecho-bearsimple#21]
按要求把文件放入theme和plugin文件夹后，点击启用，报如下错误
`Class 'Utils\Helper' not found`

**Comment by whitebearcode** [comment]
你好，主题当前需要Typecho版本为1.2正式版才能使用，请升级到1.2正式版

**Comment by Xuminhua** [comment]
谢谢。切换到1.2没问题了。之前出问题的是1.1版本
