### ISSUE TITLE
启用插件时报错 Database Query Error

### ISSUE THREAD

**Issue by Playfullycat** [whitebearcode/typecho-bearsimple#22]
数据库用的sqlite 
php 7.4
主题版本2.0.8

**Comment by whitebearcode** [comment]
目前还未在sqlite上测试通过
预计会在下个版本上适配
感谢反馈

**Comment by whitebearcode** [comment]
你好，该问题已在2.0.9版本中修复

**Comment by VincentOu0615** [comment]
数据库是mysql，Typecho版本是1.2.1，两都是用docker 部署，mysql 的IP是172.18.0.2， typecho是172.18.0.3
启动时也报：

Database Query Error

**Comment by whitebearcode** [comment]
你好

> 数据库是mysql，Typecho版本是1.2.1，两都是用docker 部署，mysql 的IP是172.18.0.2， typecho是172.18.0.3 启动时也报：
> 
> Database Query Error

这个问题待会有一个版本用于解决这个问题，感谢反馈

**Comment by whitebearcode** [comment]
> 数据库是mysql，Typecho版本是1.2.1，两都是用docker 部署，mysql 的IP是172.18.0.2， typecho是172.18.0.3 启动时也报：
> 
> Database Query Error

你好，该问题已在v2.4.3版本中修复。
