### ISSUE TITLE
如何添加评论表情？

### ISSUE THREAD

**Issue by linlinzzo** [whitebearcode/typecho-bearsimple#23]
我想给自己的网站添加 https://github.com/zkz098/mihoyoemoji 里的表情，请问我该怎么做？

**Comment by whitebearcode** [comment]
你好，可在主题目录/assets/vendors/bs-emoji/bs-emoji.json中按照格式添加
后续会出一个添加表情的文档:)

**Comment by linlinzzo** [comment]
> 你好，可在主题目录/assets/vendors/bs-emoji/bs-emoji.json中按照格式添加 后续会出一个添加表情的文档:)

但这个表情是请求一个远程地址的。大致是 https://deliver.application.pub/ ，如果直接添加的话会404。

**Comment by whitebearcode** [comment]
可以等待下一个版本2.1.1，对于表情功能会做优化。

**Comment by whitebearcode** [comment]
2.1.1版本计划在今天推送:)

**Comment by linlinzzo** [comment]
> 2.1.1版本计划在今天推送:)

Thx!

**Comment by linlinzzo** [comment]
对了，可以添加一个“关闭评论头像”的选项吗？有一些邮箱显示Cravatar的默认头像不太美观。

**Comment by whitebearcode** [comment]
没有评论头像不太美观，不过如同你说的cravatar默认头像不美观的问题，我们可以增加一个指定Cravatar默认头像地址的选项来更改默认显示的头像:)

**Comment by linlinzzo** [comment]
> 没有评论头像不太美观，不过如同你说的cravatar默认头像不美观的问题，我们可以增加一个指定Cravatar默认头像地址的选项来更改默认显示的头像:)

也可以。但还是建议弄这么一个选项。说不定有些博主就是不想显示头像呢。

**Comment by linlinzzo** [comment]
额，我刚才的想法有点杠，请不要介意。

**Comment by whitebearcode** [comment]
没事的，关闭头像的提议我们已采纳，我们还会新增设置Cravatar默认头像的选项，感谢反馈。

**Comment by whitebearcode** [comment]
你好，2.1.1版本已推送，可直接通过主题设置页面在线升级。

**Comment by linlinzzo** [comment]
现在表情的图片改成绝对地址了······很好！
那问题解决了，issue我就close了。
