### ISSUE TITLE
 v2.1.5-release issue

### ISSUE THREAD

**Issue by cuijier** [whitebearcode/typecho-bearsimple#25]
BSCore 插件版本 v2.1.5-release
主題版本 v2.1.5-release 
设置外观是就出现 Database Query Error 报错

**Comment by whitebearcode** [comment]
你好，感谢反馈
这个问题我们有注意到，触发原因可能是你的数据库开了严格模式的原因
以下两种方法可以任选一种
第一、去phpmyadmin看一下typecho_options表->结构中的value字段类型是不是mediumtext，是的话修改为longtext再看一下（这是不关闭mysql严格模式的解决办法。
第二就是关闭mysql的严格模式，严格模式会限制长度导致数据写不进去，从而导致报错

**Comment by whitebearcode** [comment]
若非此上所提到的问题，你可以将你的环境配置信息贴上，或觉得不方便公开，可发送至我的个人邮箱whitebear@msn.com

**Comment by cuijier** [comment]
> 你好，感谢反馈 这个问题我们有注意到，触发原因可能是你的数据库开了严格模式的原因 以下两种方法可以任选一种 第一、去phpmyadmin看一下typecho_options表->结构中的value字段类型是不是mediumtext，是的话修改为longtext再看一下（这是不关闭mysql严格模式的解决办法。 第二就是关闭mysql的严格模式，严格模式会限制长度导致数据写不进去，从而导致报错

按照指导，设置完毕后解决，点赞

**Comment by cuijier** [comment]
保存主题数据失败，可能是您的服务器开启了防火墙，请求被拦截，若未开启防火墙，可前往插件页面将BsCore插件卸载然后重新启用后重新启用后重试
------
又报了这个报错，是需要开启啥端口么 ？ @whitebearcode

**Comment by whitebearcode** [comment]
若没有开启防火墙且防火墙没有拦截的情况下
去插件页面对BsCore插件卸载再启用即可解决问题

**Comment by cuijier** [comment]
> 若没有开启防火墙且防火墙没有拦截的情况下 去插件页面对BsCore插件卸载再启用即可解决问题

开了防火墙，但是需要添加什么策略呢，这个不是很清楚

**Comment by whitebearcode** [comment]
若有开启CC防火墙，将拦截的请求加白即可

**Comment by whitebearcode** [comment]
或关闭POST请求拦截防护也可
