### ISSUE TITLE
巨大功能性缺陷

### ISSUE THREAD

**Issue by SlimeNull** [whitebearcode/typecho-bearsimple#3]
主页文章列表的标题不应该使用 php 直接截断, 而是应该是用 css 的 overflow hidden, text-overflow ellipsis, white-space nowrap, 否则就会出现标题长短的问题...

![image](https://user-images.githubusercontent.com/69663231/136622238-1557aff7-5118-4ef9-a43f-04cca9dc20aa.png)

(我不会 php, 只能卑微的提 issue, 而不是 pull request 了, 抱歉啦)

**Comment by sddwt** [comment]
感谢建议，回头帮你提一个pr，确实不应该截断，一来是不利于SEO，二来是中英文和数字的size不同。
