### ISSUE TITLE
[bug]主题-基础设置LOGO、图标、背景等上传按钮选择媒体内文件永远都是选择第一个文件

### ISSUE THREAD

**Issue by bit15k** [whitebearcode/typecho-bearsimple#33]
即点击主题基础设置里面的上传LOGO、图标等上传按钮，选择媒体库内的文件，无论选择哪一个最后都是选择成了第一个文件

BearSimple主题版本：V2.3.9.20230918[[更新日志](https://docs.whitebear.dev/index.php/archives/6/)]
PHP版本：7.4.33
网站服务器：nginx/1.24.0
数据库：Pdo_SQLite[Version：3.43.1]
Typecho版本：1.2.1
User Agent信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.36

**Comment by whitebearcode** [comment]
问题已收到，感谢反馈
