### ISSUE TITLE
关于“登录或回复后可见”功能的优化建议

### ISSUE THREAD

**Issue by bit15k** [whitebearcode/typecho-bearsimple#34]
1. 当后台设置了“评论不需要审核”，评论发表完后建议增加局部刷新文章，让文章隐藏内容显示出来。现在的逻辑是只刷新评论区，文章区不会刷新，只能自己去刷新网页才能看到隐藏内容。假如我是读者，不知道的会感觉受到了欺骗，会离开网页而不是去手动刷新。

2. 当插入短代码登录或回复后可见，现在显示的是“此处内容需要登录或评论回复 (审核通过) 后方可显示”，可以删除掉审核通过这几个字。或者可以和后台设置联动，当设置成“评论需要审核”那就显示“此处内容需要登录或评论回复 (审核通过) 后方可显示”，如果后台没开启评论审核，那就显示“此处内容需要登录或评论回复后方可显示”；或者直接做成可以自定义显示的内容。

上述是细节建议，希望考虑，我感觉这这有助于提升访客的停留率，比如1访客留言了，但没看到隐藏内容显示，就走了；比如2很多人看到留言需要审核就跑了，实际上是不需要审核。

**Comment by whitebearcode** [comment]
好的，我们会在下一个版本中对此进行优化，感谢
