### ISSUE TITLE
演示站提示字体文件跨域失败

### ISSUE THREAD

**Issue by eezd** [whitebearcode/typecho-bearsimple#35]
# 问题

你好请问下是我本地环境有问题吗？

因为我在Chrome 、Firefox 、手机EDGE浏览器上试了都是这样。

编辑：开全局代理正常显示，请问有解决办法吗？

Chrome：
![image](https://github.com/whitebearcode/typecho-bearsimple/assets/59011602/c2a80255-00af-42c0-b5d9-c6140d4ceb94)

手机EDGE：缺少图标
![image](https://github.com/whitebearcode/typecho-bearsimple/assets/59011602/df0f0d1a-a182-45fe-b507-7411b05bee2a)

```
Access to CSS stylesheet at 'https://cdn.staticfile.org//font-awesome/5.15.4/css/v4-shims.min.css?ver=5.15.4' from origin 'https://bearsimple.typecho.ru' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://rumosky.com' that is not equal to the supplied origin.
```

# 环境
Chrome 版本 121.0.6167.8（正式版本）beta （64 位）
Firefox 120.0.1 64位

**Comment by whitebearcode** [comment]
你好，这个问题为staticfile.org CDN回源问题，需等待staticfile官方处理
下个版本会对静态资源问题进行优化，感谢反馈

**Comment by eezd** [comment]
好的，感谢你的回复
