### ISSUE TITLE
V2.5.2.20240121 版本rss输出乱码

### ISSUE THREAD

**Issue by Sualiu** [whitebearcode/typecho-bearsimple#36]
BearSimple主题版本：V2.5.2.20240121
PHP版本：8.3.1
Typecho版本：1.2.1

问题地址： example.com/feed   &&  example.com/feed/rss

如图：

![image](https://github.com/whitebearcode/typecho-bearsimple/assets/42514208/6caff020-a5cc-4772-a621-cb87254746b0)

**Comment by Sualiu** [comment]
抱歉，似乎只存在乱码问题。之前的输出源代码的表述错误。

**Comment by whitebearcode** [comment]
输出编码问题，该问题已处理
