### ISSUE TITLE
侧边栏文章目录树无法准确定位文章标题

### ISSUE THREAD

**Issue by Sualiu** [whitebearcode/typecho-bearsimple#37]
BearSimple主题版本：V2.5.2.20240121
PHP版本：8.3.1

数据库：Pdo_Mysql[Version：5.7.44-log]
Typecho版本：1.2.1

文章页面：
![image](https://github.com/whitebearcode/typecho-bearsimple/assets/42514208/e5b0e95f-dfb0-4238-bbaa-6925761a8b1f)

点击侧边栏目录“谷歌语法-信息收集”：
![image](https://github.com/whitebearcode/typecho-bearsimple/assets/42514208/ce2d21ed-bf3b-4b91-a336-4b83ab14f5b6)

可以看到跳转到的标题位置较实际标题位置明显靠下。

**Comment by whitebearcode** [comment]
收到问题，下个版本中处理，感谢反馈😃
