### ISSUE TITLE
pjax 重载问题

### ISSUE THREAD

**Issue by SlimeNull** [whitebearcode/typecho-bearsimple#4]
例如我从主页点进去一个文章, 并滑到文章最底部, 当我是用浏览器的后退功能返回到主页时, 页面位置保持在了底部, 而不是重新回滚到原来的位置, 或者是顶部. (保持在底部太生草了真的), 就是这样:

![image](https://user-images.githubusercontent.com/69663231/136622588-4733d775-c1bc-4ec9-8e74-bc16a3f78529.png)

**Comment by applemiku** [comment]
同样遇到这个问题（
